= Migrate a devon4j project to the latest version
== Some subtitle
====
The java commandlet allows to setup Java. Also it supports devon4j. The arguments (devon java «args») are explained by the below details: 
https://devonfw.com/website/pages/docs/devonfw-ide-usage.asciidoc.html#java.asciidoc

This tutorial mainly focuses on to migrate an old version of devon4j project to the latest version.
## Prerequisites
* devonfw IDE

## Learning goals.
Here in this tutorial you will learn 
* How to migrate an older version of devon4j project to the latest version.

====


Install older version of devonfw ( "2020.08.001")
[step]
--
restoreDevonfwIde(["java","mvn"])
--

Now, we will create a sample devon4j application with the name *sampleapp*.
[step]
--
executeCommand("mvn -DarchetypeVersion=3.0.1 -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate", "mvn -DarchetypeVersion=3.0.1 -DarchetypeGroupId=com.devonfw.java.templates -DarchetypeArtifactId=devon4j-template-server archetype:generate", {"args":["-DgroupId=com.example.application", "-DartifactId=sampleapp", "-Dversion=1.0.0-SNAPSHOT", "-Dpackage=com.devonfw.application.sampleapp", "-DinteractiveMode=false"] })
--


In the below step it will execute "devon java migrate".
[step]
--
executeCommand("devon java migrate", "devon java migrate", {"dir": "sampleapp"})
--


====
## Conclusion

In this tutorial you have learnt How to migrate an older version of devon4j project to the latest version using command line.

====


